77-feature-add-collaboration-section
IT-Academy-BCN/ita-profiles-frontend pull request #86
Opened 2024-03-07 16:11 UTC by treee97

# Changes

- Added the collaboration section as shown in figma.
- Responsive, works well on all screens.

View on large screens:

![image](https://github.com/IT-Academy-BCN/ita-profiles-frontend/assets/116231527/0391cde9-28af-46bb-b607-8f46ebbbd040)

View on small screens:

![image](https://github.com/IT-Academy-BCN/ita-profiles-frontend/assets/116231527/e06d724f-2950-48be-875b-b7dde935c3cc)

2024-03-08 23:40 UTC, Stefis0702 commented
Se ve muy bien..!!

2024-03-08 23:41 UTC, Stefis0702 reviewed
Se ve muy bien..!

2024-03-11 08:48 UTC, monica-mp approved these changes
Good job!

2024-03-11 08:52 UTC, Stefis0702 approved these changes
Se ve muy bien

2024-03-11 10:16 UTC, Laucf7 commented
se ve perfecto!

2024-03-11 11:13 UTC, llopFilms requested changes
- Podries fer el component amb el nom Collabortaion, Challenges  i Resources a seques? Estem posant els noms al component del títol de la Card

2024-03-11 12:07 UTC, jordimorillo approved these changes

2024-03-11 13:02 UTC, llopFilms approved these changes

2024-03-11 13:07 UTC, Laucf7 approved these changes

2024-03-11 15:22 UTC, merged