Feature/75 fe crear el componente user data user about skill
IT-Academy-BCN/ita-profiles-frontend pull request #90
Opened 2024-03-13 16:19 UTC by jordimorillo

2024-03-13 16:46 UTC, treee97 commented on src/components/userDetailsPanel/studentData/StudentData.tsx
> +                    <img
las img de "bookmark" y "email" no son necesarias de momento.Se tienen que quitar.
En mi PR las puse en su momento porque no tenía idea de lo que estaba haciendo. En un futuro sí se utilizaran cuando hagamos el apartado de recruiter 👍

2024-03-13 22:26 UTC, Dar-ya218 commented
Despues de abordar la sugerencia de Luiggi, el resto se ve muy bien. ¡Felicidades por vuestro progreso!

2024-03-13 22:27 UTC, Dar-ya218 approved these changes

2024-03-13 23:32 UTC, llopFilms requested changes
- El nom del component crec que hauria de ser StudentDataCard, perquè tots els components els estem anomenant Card
- Jo faria servir Rect.FC per tipar el component amb les propietats de ReactTS
- Importaria les imatges png i svg fent servir l'index.ts que hi ha a la carpeta img i svg
- Cal fer servir els colors de tailwind config.js
- El nom de l'estudiant hauria de ser un H3
- 'About' hauria de ser un H4
- La resta, p
- Jo sóc partidari de no posar margins i posar paddings (per conservar la mida de l'element)
-

2024-03-18 11:30 UTC, llopFilms approved these changes

2024-03-18 11:37 UTC, merged