Feature/#81 fe add modalidad component in student detail view
IT-Academy-BCN/ita-profiles-frontend pull request #91
Opened 2024-03-13 17:05 UTC by leidyz

same as figma

2024-03-13 22:36 UTC, Dar-ya218 approved these changes
Good job, you get it. Congratulations!

2024-03-13 23:18 UTC, llopFilms requested changes
Està molt bé!
Petites millores que jo proposo per temes de semàntica, noms, etc...
- Per un component tant petit jo no faria servir daisyui
- Jo ho faria tot amb flex + gap (sense padding)
- El títol ha de ser un H3
- La modalitat hauria de ser un p
- Faltaria formatejar el codi?
- No cal la classe row (és row per defecte)

2024-03-18 11:30 UTC, llopFilms approved these changes

2024-03-18 16:39 UTC, treee97 commented on src/components/studentDetailCards/modalitySection/modalityCard.tsx
> +            <h1 className="font-bold pb-5 pt-8 text-lg">Modalidad</h1>
Hola!! Solo puede haber un H1 por página web, por cosas de SEO 🤔
Lo mismo sería para un H2, que creo que pueden haber un par o 3 como máximo en toda la web. 
Puedes cambiarlos a un div o una p que sería más apropiado para accesibilidad. 
El resto todo perfecto pero en la línea 10 de este archivo tienes un w-full con un espacio! 👍 👍

2024-03-19 11:32 UTC, jordimorillo commented
@leidyz please resolve the conflicts and do merge :)

2024-03-21 12:07 UTC, llopFilms commented on src/components/studentDetailCards/modalitySection/modalityCard.tsx
> +            <h1 className="font-bold pb-5 pt-8 text-lg">Modalidad</h1>
Solucionat

2024-03-21 12:08 UTC, merged