Feature/80 fe add a idiomas component in student detail view
IT-Academy-BCN/ita-profiles-frontend pull request #92
Opened 2024-03-13 22:09 UTC by Dar-ya218

- [x] Lenguage component made
![image](https://github.com/IT-Academy-BCN/ita-profiles-frontend/assets/123471637/24c108a1-6ce3-45ea-95f8-9ea7879329c0)

2024-03-13 23:12 UTC, llopFilms requested changes
- El nom del component hauria de ser 'LanguageCard'
- Faltaria formatejar el codi
- Jo ho faria tot amb flex + gap (sense padding)
- El títol de la card ha de ser un H3
- El idiomes han de ser p

2024-03-17 21:12 UTC, llopFilms approved these changes

2024-03-17 21:31 UTC, Dar-ya218 commented
Refactored code according to Jordi's suggestions, and the desing aligns with Figma.

2024-03-19 09:01 UTC, Stefis0702 approved these changes
Muy bien ..!!

2024-03-19 10:06 UTC, treee97 approved these changes

2024-03-19 11:31 UTC, jordimorillo commented
@Dar-ya218 soluciona los conflictos y haz merge

2024-03-19 22:38 UTC, merged